project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("newpage.html", views.newPage, name="newPage"),
    path("editwiki.html", views.editWiki, name="editWiki"),
    path("randompage", views.randomPage, name="randomPage"),
    path("<str:entryName>", views.entryName, name="entryName")
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/views.py
from django.shortcuts import render

from . import util

from django import forms
import markdown
import random

# remove after, for testing
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

#index page
def index(request):

    #load all entries
    if request.method == "GET":
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })

    #if search used
    else:
        searchRequest = request.POST.get("q")

        #if match found, load page for that entry
        for entry in util.list_entries():
            if searchRequest.lower() == entry.lower():
                return render(request, "encyclopedia/entry.html", {
                "content": markdown.markdown(util.get_entry(searchRequest)),
                "entryName": searchRequest.capitalize()
            })

        #if match not found, display a page with possible matches
        else:
            subentryList = []
            for entry in util.list_entries():
                if searchRequest.lower() in entry.lower():
                    subentryList.append(entry)

            subentryList.sort()

            return render(request, "encyclopedia/index.html", {
                "entries": subentryList
            })

#if page access attempted through search bar / eg. /http
def entryName(request, entryName):

    #convert all page names to lowercase
    lowercaseList = []
    for entries in util.list_entries():
        lowercaseList.append(entries.lower())

    #check if new name exists, if not found display not found and possible entries
    if entryName.lower() not in lowercaseList:
        return render(request, "encyclopedia/notfound.html", {
            "entries": util.list_entries()
        })

    #if found, pull page for that entry
    else:
        return render(request, "encyclopedia/entry.html", {
            "content": markdown.markdown(util.get_entry(entryName)),
            "entryName": entryName.capitalize()
        })

#create form for new page
class newContent(forms.Form):
    title = forms.CharField(label="New Title")
    content = forms.CharField(widget=forms.Textarea, label="New Content")

#load new GET for new Page with form for user to fill in
def newPage(request):
    if request.method == "GET":
        return render(request, "encyclopedia/newpage.html", {
            "newPage": newContent()
        })

    #If user submits form
    else:
        form = newContent(request.POST)

        #Check server side that form is valid, decompose data into smaller pieces
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            #convert all page names to lowercase
            lowercaseList = []
            for entries in util.list_entries():
                lowercaseList.append(entries.lower())

            #render error if title is already taken
            if title.lower() in lowercaseList:
                return render(request, "encyclopedia/pageexists.html")

            #redirect to new wiki if save is successful
            else:
                util.save_entry(title.capitalize(), content)
                return HttpResponseRedirect(reverse("encyclopedia:entryName", kwargs = {'entryName' : title}))

#create form to edit existing wiki
class editContent(forms.Form):
    content = forms.CharField(widget=forms.Textarea, label="New Content")
    title = forms.CharField(widget=forms.HiddenInput())

def editWiki(request):
    #if navigating to editwiki page from previous page
    if request.method == "GET":
        #get content and title
        content = util.get_entry(request.GET.get("title"))
        title = request.GET.get("title")
        for entries in util.list_entries():
            if title.lower() == entries.lower():
                title = entries

        #display editor for content and title
        return render(request, "encyclopedia/editwiki.html", {
            "newContent": editContent(initial={"content": content, "title": title}),
            "content": content,
            "title": title
        })

    #if user saves new change
    else:
        title = request.POST.get("title")
        content = request.POST.get("content")
        util.save_entry(title.capitalize(), content)
        return HttpResponseRedirect(reverse("encyclopedia:entryName", kwargs = {'entryName' : title}))

#select random page from list of entries
def randomPage(request):
    wikis = util.list_entries()
    randomSelect = random.choice(wikis)
    return HttpResponseRedirect(reverse("encyclopedia:entryName", kwargs = {'entryName' : randomSelect}))

project1/wiki/encyclopedia/templates/encyclopedia/editwiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit wiki: {{ title }}
{% endblock %}

{% block body %}

    <h1>Edit existing wiki: {{ title }} </h1>
    <div>
    <form action="{% url 'encyclopedia:editWiki' %}" method="POST">
        {% csrf_token %}
        <div>
            <p>
                {{ newContent }}
            </p>
        </div>
        <div>
            <input type="submit">
        </div>
        </div>
    </form>
    </div>    

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entryName }}
{% endblock %}

{% block body %}

    {{ content|safe }}

    <p>
        <form action="{% url 'encyclopedia:editWiki' %}" method="GET">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ entryName }}">
            <input type="hidden" name="content" value="{{ content }}">
            <input type="submit" value="Edit wiki">
        </form>
    </p>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new page
{% endblock %}

{% block body %}

    <h1>Create new page</h1>
    <div>
    <form action="{% url 'encyclopedia:newPage' %}" method="POST">
        {% csrf_token %}
        <div>
            <p>
                {{ newPage }}
            </p>
        </div>
        <div>
            <input type="submit">
        </div>
        </div>
    </form>
    </div>  

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry not found
{% endblock %}

{% block body %}
    <h1>Entry not found</h1>

    <p>
        Unknown entry, please try another.
    </p>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/pageexists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error: page already exists
{% endblock %}

{% block body %}
    <h1>Error, page already exists.</h1>

    <p>
        Please try to create an entry under another name, or edit the existing entry.
    </p>

{% endblock %}